version: '3.8'

services:
  db:
    image: postgres:15.14-alpine3.21
    container_name: "db"
    environment:
    - POSTGRES_DB=edu_platform
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=password
    ports:
     - "5432:5432"
    networks:
      network:
        ipv4_address: 172.40.0.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d edu_platform"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: python_app
    ports:
     - "8000:8000"
    volumes:
      - ./app:/app/app
    networks:
      network:
        ipv4_address: 172.40.0.3
    depends_on:
      db:
        condition: service_healthy

  web:
    image: nginx:latest_modificated
    container_name: web
    ports:
     - "80:80"
     - "443:443"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d:rw
    networks:
      network:
        ipv4_address: 172.40.0.4
    command: /bin/bash -c "mkcert localhost && service nginx restart && tail -f /dev/null"

networks:
  network:
    driver: bridge
    ipam:
      config:
       - subnet: 172.40.0.0/24
